// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieApiMvc.DataBaseAccess;

#nullable disable

namespace MovieApiMvc.DataBaseAccess.Migrations
{
    [DbContext(typeof(MovieDataBaseContext))]
    [Migration("20241001204510_CreateUsersRoles")]
    partial class CreateUsersRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("CountryEntityMovieEntity", b =>
                {
                    b.Property<Guid>("CountriesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MoviesId")
                        .HasColumnType("TEXT");

                    b.HasKey("CountriesId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("CountryEntityMovieEntity");
                });

            modelBuilder.Entity("GenreEntityMovieEntity", b =>
                {
                    b.Property<Guid>("GenresId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MoviesId")
                        .HasColumnType("TEXT");

                    b.HasKey("GenresId", "MoviesId");

                    b.HasIndex("MoviesId");

                    b.ToTable("GenreEntityMovieEntity");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.BudgetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("Budgets", (string)null);
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.CountryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries", (string)null);
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.GenreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres", (string)null);
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.ImageInfoEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PreviewUrls")
                        .HasColumnType("TEXT");

                    b.Property<string>("Urls")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternativeName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSeries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MovieLength")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("TEXT");

                    b.Property<int>("Top250")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Movies", (string)null);
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.RatingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<short?>("FilmCritics")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Imdb")
                        .HasColumnType("INTEGER");

                    b.Property<short?>("Kp")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("MovieId")
                        .HasColumnType("TEXT");

                    b.Property<short?>("RussianFilmCritics")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MovieId")
                        .IsUnique();

                    b.ToTable("Ratings", (string)null);
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.RoleEntitiy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("MovieEntityUserEntity", b =>
                {
                    b.Property<Guid>("FavMovieUsersId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FavMoviesId")
                        .HasColumnType("TEXT");

                    b.HasKey("FavMovieUsersId", "FavMoviesId");

                    b.HasIndex("FavMoviesId");

                    b.ToTable("MovieEntityUserEntity");
                });

            modelBuilder.Entity("MovieEntityUserEntity1", b =>
                {
                    b.Property<Guid>("WatchLaterMoviesId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WatchLaterUsersId")
                        .HasColumnType("TEXT");

                    b.HasKey("WatchLaterMoviesId", "WatchLaterUsersId");

                    b.HasIndex("WatchLaterUsersId");

                    b.ToTable("MovieEntityUserEntity1");
                });

            modelBuilder.Entity("CountryEntityMovieEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.CountryEntity", null)
                        .WithMany()
                        .HasForeignKey("CountriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreEntityMovieEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.GenreEntity", null)
                        .WithMany()
                        .HasForeignKey("GenresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("MoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.BudgetEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", "Movie")
                        .WithOne("Budget")
                        .HasForeignKey("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.BudgetEntity", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.ImageInfoEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", "Movie")
                        .WithOne("ImageInfoEntity")
                        .HasForeignKey("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.ImageInfoEntity", "MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.RatingEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", "Movie")
                        .WithOne("Rating")
                        .HasForeignKey("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.RatingEntity", "MovieId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.UserEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.RoleEntitiy", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MovieEntityUserEntity", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("FavMovieUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("FavMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieEntityUserEntity1", b =>
                {
                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", null)
                        .WithMany()
                        .HasForeignKey("WatchLaterMoviesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("WatchLaterUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.MovieEntities.MovieEntity", b =>
                {
                    b.Navigation("Budget");

                    b.Navigation("ImageInfoEntity");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("MovieApiMvc.DataBaseAccess.Entities.UsersEntities.RoleEntitiy", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
