GET http://localhost:5128/api/movies

###

GET http://localhost:5128/api/movies/page?pageNumber = 2&pageSize = 20

###

GET http://localhost:5128/api/movies/46F95B7C-CC87-4FB0-8C92-0D49FF931115

###

GET http://localhost:5128/api/movies/images

###

GET http://localhost:5128/api/movies/7C0C2DE0-3DB6-48E6-971C-47A69E7BF5F6

###

GET http://localhost:5128/api/movies/7C0C2DE0-3DB6-48E6-971C-47A69E7BF5F6/images

###


PUT http://localhost:5128/api/movies
Content-Type: application/json
id: d97222b3-702f-4c1f-84b4-2117e94729f9

{
  "name": "Больше это нихуя не приключения рейми",
  "RatingKp": 8.018,
  "RatingFilmCritics": 8.018,
  "type": "movie",
  "year": 2002,
  "alternativeName": "fgbjkl",
  "top250": 122
}

###

POST http://localhost:5128/api/movies
Content-Type: application/json

{
  "name": null,
  "RatingKp": 8.018,
  "RatingFilmCritics": 8.018,
  "type": "movie",
  "year": 2002,
  "alternativeName": "fgbjkl",
  "top250": 122
}

###

DELETE http://localhost:5128/api/movies/9C9591A6-0CF9-409B-9B5D-A1E675E46974

###

POST http://localhost:5128/api/users/login
Content-Type: application/json

{
  "Email": "john.doe@example.com",
  "Password": "hashed_password"
}

###
POST http://localhost:5128/api/users/login
Content-Type: application/json

{
  "Email": "email@email",
  "Password": "passw"
}

###

GET http://localhost:5128/api/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiNGU0NmZhNzYtZjVlNy00ZGQwLWFjMGMtNzA0Mjk0MzA2MWMzIiwiZXhwIjoxNzI1MDU3NjExfQ.TUrl9lq1uRVk5fmrbQ7x7zc6m4DoSW9dE8xTAxeH90k

### 
POST http://localhost:5128/api/users
Content-Type: application/json

{
  "UserName": "user2",
  "Password": "hashed_password",
  "Email": "short@s.com",
  "FavMovies": [
  ],
  "WatchLaterMovies": [
  ]
}

### 

POST http://localhost:5128/api/users/addToWatchList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzaG9ydEBzLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZWJlNGUxYTgtMjlhOS00NzM1LWJjZjEtNzU2OWFiYzAxNDkwIiwiZXhwIjoxNzI1MTk5MDQxfQ.u5-tbYn-BKEstwG1ka4k9oOottnS1CFet3FlGs2iExQ

[
  "1AC0B13F-B271-4F94-9A8A-4D0C2E754C73"
]

###

DELETE http://localhost:5128/api/users/1AC0B13F-B271-4F94-9A8A-4D0C2E754C73/removeFromWatchList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzaG9ydEBzLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZWJlNGUxYTgtMjlhOS00NzM1LWJjZjEtNzU2OWFiYzAxNDkwIiwiZXhwIjoxNzI1MTk5MDQxfQ.u5-tbYn-BKEstwG1ka4k9oOottnS1CFet3FlGs2iExQ

### 

POST http://localhost:5128/api/users
Content-Type: application/json

{
  "UserName": "aabbcc",
  "PasswHash": "hashed_password2",
  "Email": "aabbcc@example.com",
  "FavMovies": [
  ],
  "WatchLaterMovies": [
  ]
}

###

POST http://localhost:5128/api/users/login
Content-Type: application/json

{
  "password": "hashed_password",
  "email": "short@s.com"
}

###

GET http://localhost:5128/api/users/watchList
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzaG9ydEBzLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWVpZGVudGlmaWVyIjoiZWJlNGUxYTgtMjlhOS00NzM1LWJjZjEtNzU2OWFiYzAxNDkwIiwiZXhwIjoxNzI1MTk5MDQxfQ.u5-tbYn-BKEstwG1ka4k9oOottnS1CFet3FlGs2iExQ

###

GET http://localhost:5128/api/users/GetTestAuth
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJzaG9ydEBzLmNvbSIsImV4cCI6MTcyNDYwMzYxMH0.-j5-OqmdOuUmlaXniC_VxA32eremis4KMzAvz-XB1ME

### 